baseURL: "http://example.org/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "anubis"

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 2
    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 2
    - identifier: archive
      name: Archive
      title: Archive
      url: /blog/
      weight: 0

params:
  paginationSinglePost: true
  style: auto
  readMore: true

markup:
  highlight:
    style: dracula
